name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run type checking
      run: bun run typecheck

    - name: Run linter
      run: bun run lint

    - name: Run tests
      run: bun test

    - name: Build project
      run: bun run build

    - name: Verify version consistency
      run: |
        PACKAGE_VERSION="v$(node -p "require('./package.json').version")"
        if [ "$PACKAGE_VERSION" != "${{ github.ref_name }}" ]; then
          echo "Error: Package version ($PACKAGE_VERSION) does not match tag (${{ github.ref_name }})"
          exit 1
        fi
        echo "Version check passed: $PACKAGE_VERSION"

    - name: Create tarball
      run: |
        tar -czf wallet-agent-${{ github.ref_name }}.tar.gz dist/ package.json README.md LICENSE

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: wallet-agent-${{ github.ref_name }}.tar.gz
        retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: wallet-agent-${{ github.ref_name }}.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}

  publish-npm:
    name: Publish to npm
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build project
      run: bun run build

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}